<a href="https://colab.research.google.com/github/biswajitmaharana2016/C-/blob/master/Pandas22ndJune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [2]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)

In [5]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s1.shape

(5,)

In [8]:
s1.size

5

In [9]:
s1.values

array([1, 2, 3, 4, 5])

In [11]:
type(s1.values)

numpy.ndarray

In [13]:
s2= pd.Series([1,2+1j,'krishna',40.5,5+2j], index=['a','b','c','d','e'])
s2

a          1
b     (2+1j)
c    krishna
d       40.5
e     (5+2j)
dtype: object

In [14]:
s2[0:3]

a          1
b     (2+1j)
c    krishna
dtype: object

In [21]:
s2['a':'c']

a          1
b     (2+1j)
c    krishna
dtype: object

In [23]:
s2['c']= s2['c'] + 'mohan'
s2

a                    1
b               (2+1j)
c    krishnamohanmohan
d                 40.5
e               (5+2j)
dtype: object

In [24]:
type(s2)

pandas.core.series.Series

In [27]:
s1[(s1 >2) & (s1 < 5)]

2    3
3    4
dtype: int64

In [28]:
s1[(s1 >=2) | (s1 <= 5)]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
s1[~(s1 > 2)]

0    1
1    2
dtype: int64

In [35]:
data = {
    'name': ['Raja', 'Rakesh','Rana','Lakshmi', 'Mario'],
    'city': ['Munich','Hmburg','Blore','Hyd','Delhi'],
    'job': ['Admin','Dev','Arch','CTO','Manager']
}
df1 = pd.DataFrame(data)
df1

      name    city      job
0     Raja  Munich    Admin
1   Rakesh  Hmburg      Dev
2     Rana   Blore     Arch
3  Lakshmi     Hyd      CTO
4    Mario   Delhi  Manager

In [40]:
df1['name'][0]

'Raja'

In [42]:
df1.city[0]

'Munich'

In [43]:
df1.columns =['name of per', 'city', 'job']

In [44]:
df1

  name of per    city      job
0        Raja  Munich    Admin
1      Rakesh  Hmburg      Dev
2        Rana   Blore     Arch
3     Lakshmi     Hyd      CTO
4       Mario   Delhi  Manager

In [45]:
df1.rename(columns={'name of per':'name'}, inplace=True)

In [46]:
df1

      name    city      job
0     Raja  Munich    Admin
1   Rakesh  Hmburg      Dev
2     Rana   Blore     Arch
3  Lakshmi     Hyd      CTO
4    Mario   Delhi  Manager

In [50]:
df1[['name', 'job','city']]

      name      job    city
0     Raja    Admin  Munich
1   Rakesh      Dev  Hmburg
2     Rana     Arch   Blore
3  Lakshmi      CTO     Hyd
4    Mario  Manager   Delhi

In [52]:
df1.loc[0]

name      Raja
city    Munich
job      Admin
Name: 0, dtype: object

In [55]:
df1.iloc[2]['name']

'Rana'

In [56]:
df1.index =['a','b','c','d','e']

In [57]:
df1

      name    city      job
a     Raja  Munich    Admin
b   Rakesh  Hmburg      Dev
c     Rana   Blore     Arch
d  Lakshmi     Hyd      CTO
e    Mario   Delhi  Manager

In [60]:
df1.loc['a']['name'] # loc function can be any thing other than integer

'Raja'