<a href="https://colab.research.google.com/github/biswajitmaharana2016/C-/blob/master/Pandas22ndJune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [2]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)

In [5]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s1.shape

(5,)

In [8]:
s1.size

5

In [9]:
s1.values

array([1, 2, 3, 4, 5])

In [11]:
type(s1.values)

numpy.ndarray

In [13]:
s2= pd.Series([1,2+1j,'krishna',40.5,5+2j], index=['a','b','c','d','e'])
s2

a          1
b     (2+1j)
c    krishna
d       40.5
e     (5+2j)
dtype: object

In [14]:
s2[0:3]

a          1
b     (2+1j)
c    krishna
dtype: object

In [21]:
s2['a':'c']

a          1
b     (2+1j)
c    krishna
dtype: object

In [23]:
s2['c']= s2['c'] + 'mohan'
s2

a                    1
b               (2+1j)
c    krishnamohanmohan
d                 40.5
e               (5+2j)
dtype: object

In [24]:
type(s2)

pandas.core.series.Series

In [27]:
s1[(s1 >2) & (s1 < 5)]

2    3
3    4
dtype: int64

In [28]:
s1[(s1 >=2) | (s1 <= 5)]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
s1[~(s1 > 2)]

0    1
1    2
dtype: int64

In [35]:
data = {
    'name': ['Raja', 'Rakesh','Rana','Lakshmi', 'Mario'],
    'city': ['Munich','Hmburg','Blore','Hyd','Delhi'],
    'job': ['Admin','Dev','Arch','CTO','Manager']
}
df1 = pd.DataFrame(data)
df1

      name    city      job
0     Raja  Munich    Admin
1   Rakesh  Hmburg      Dev
2     Rana   Blore     Arch
3  Lakshmi     Hyd      CTO
4    Mario   Delhi  Manager

In [40]:
df1['name'][0]

'Raja'

In [42]:
df1.city[0]

'Munich'

In [43]:
df1.columns =['name of per', 'city', 'job']

In [44]:
df1

  name of per    city      job
0        Raja  Munich    Admin
1      Rakesh  Hmburg      Dev
2        Rana   Blore     Arch
3     Lakshmi     Hyd      CTO
4       Mario   Delhi  Manager

In [45]:
df1.rename(columns={'name of per':'name'}, inplace=True)

In [46]:
df1

      name    city      job
0     Raja  Munich    Admin
1   Rakesh  Hmburg      Dev
2     Rana   Blore     Arch
3  Lakshmi     Hyd      CTO
4    Mario   Delhi  Manager

In [50]:
df1[['name', 'job','city']]

      name      job    city
0     Raja    Admin  Munich
1   Rakesh      Dev  Hmburg
2     Rana     Arch   Blore
3  Lakshmi      CTO     Hyd
4    Mario  Manager   Delhi

In [52]:
df1.loc[0]

name      Raja
city    Munich
job      Admin
Name: 0, dtype: object

In [55]:
df1.iloc[2]['name']

'Rana'

In [56]:
df1.index =['a','b','c','d','e']

In [57]:
df1

      name    city      job
a     Raja  Munich    Admin
b   Rakesh  Hmburg      Dev
c     Rana   Blore     Arch
d  Lakshmi     Hyd      CTO
e    Mario   Delhi  Manager

In [60]:
df1.loc['a']['name'] # loc function can be any thing other than integer

'Raja'

In [61]:
df1.query('name == "Raja"' and 'city == "Munich"')

   name    city    job
a  Raja  Munich  Admin

In [62]:
df1["salary"]=[1000,2000,3000,4000,5000]

In [63]:
df1

      name    city      job  salary
a     Raja  Munich    Admin    1000
b   Rakesh  Hmburg      Dev    2000
c     Rana   Blore     Arch    3000
d  Lakshmi     Hyd      CTO    4000
e    Mario   Delhi  Manager    5000

In [65]:
cond1 = df1['salary'] > 2000
cond2 = df1['salary'] < 5000

In [66]:
df1[cond1 & cond2]

      name   city   job  salary
c     Rana  Blore  Arch    3000
d  Lakshmi    Hyd   CTO    4000

In [67]:
name_list = ['Raja','Mario']
df1[df1['name'].isin(name_list)]

    name    city      job  salary
a   Raja  Munich    Admin    1000
e  Mario   Delhi  Manager    5000

In [68]:
df1[df1.name.str.startswith('R')]

     name    city    job  salary
a    Raja  Munich  Admin    1000
b  Rakesh  Hmburg    Dev    2000
c    Rana   Blore   Arch    3000

In [69]:
df1.name.str.upper

In [70]:
df1[df1.salary == df1.salary.max()]

    name   city      job  salary
e  Mario  Delhi  Manager    5000

In [71]:
df1.sort_values(by='salary', ascending=False)

      name    city      job  salary
e    Mario   Delhi  Manager    5000
d  Lakshmi     Hyd      CTO    4000
c     Rana   Blore     Arch    3000
b   Rakesh  Hmburg      Dev    2000
a     Raja  Munich    Admin    1000

In [72]:
df1.reset_index()

  index     name    city      job  salary
0     a     Raja  Munich    Admin    1000
1     b   Rakesh  Hmburg      Dev    2000
2     c     Rana   Blore     Arch    3000
3     d  Lakshmi     Hyd      CTO    4000
4     e    Mario   Delhi  Manager    5000

In [75]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Berlin', 'Paris', 'London']
})

# Save to CSV
df.to_csv('output.csv', index=False)

In [81]:
df.to_json('output.json')

In [83]:
df.to_excel('output.xlsx', index=False)

In [77]:
pd.read_csv('output.csv')

      Name  Age    City
0    Alice   25  Berlin
1      Bob   30   Paris
2  Charlie   35  London

In [79]:
pd.read_table('output.csv', sep=',')

      Name  Age    City
0    Alice   25  Berlin
1      Bob   30   Paris
2  Charlie   35  London

In [82]:
pd.read_json('output.json')

      Name  Age    City
0    Alice   25  Berlin
1      Bob   30   Paris
2  Charlie   35  London

In [84]:
pd.read_excel('output.xlsx')

      Name  Age    City
0    Alice   25  Berlin
1      Bob   30   Paris
2  Charlie   35  London

In [86]:
df2 =pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [88]:
df2.to_csv('titanic.csv', index=False)

In [89]:
pd.read_csv('titanic.csv', index_col='PassengerId')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [97]:
ship = pd.read_csv('titanic.csv')
ship

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [98]:
df2= pd.read_csv('titanic.csv', usecols=['PassengerId','Survived','Pclass'])

In [103]:
df2.insert(2,'Harris',ship.Name)

In [106]:
df.insert(2,'Biswajit',ship.Name)

In [108]:
ship.insert(2,'Biswajit',ship.Name)

In [109]:
ship

,PassengerId,Survived,Biswajit,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,"Braund, Mr. Owen Harris",3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,"Heikkinen, Miss. Laina",3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,"Allen, Mr. William Henry",3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,"Dooley, Mr. Patrick",3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [110]:
ship.columns

Index(['PassengerId', 'Survived', 'Biswajit', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [111]:
ship.drop('Embarked', axis=1, inplace=True)

In [112]:
ship.columns

Index(['PassengerId', 'Survived', 'Biswajit', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin'],
      dtype='object')

In [113]:
ship.drop(4, axis=0, inplace=True)

In [114]:
ship

,PassengerId,Survived,Biswajit,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,"Braund, Mr. Owen Harris",3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,1,"Heikkinen, Miss. Laina",3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
5,6,0,"Moran, Mr. James",3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
887,888,1,"Graham, Miss. Margaret Edith",1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,890,1,"Behr, Mr. Karl Howell",1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
890,891,0,"Dooley, Mr. Patrick",3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN

In [115]:
ship.reset_index(drop=True, inplace=True)

In [116]:
ship

,PassengerId,Survived,Biswajit,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,"Braund, Mr. Owen Harris",3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,1,"Heikkinen, Miss. Laina",3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
4,6,0,"Moran, Mr. James",3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,"Montvila, Rev. Juozas",2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
886,888,1,"Graham, Miss. Margaret Edith",1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42
887,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
888,890,1,"Behr, Mr. Karl Howell",1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
889,891,0,"Dooley, Mr. Patrick",3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN

In [117]:
ship.columns

Index(['PassengerId', 'Survived', 'Biswajit', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin'],
      dtype='object')

In [118]:
ship.drop(['Survived'], axis=1, inplace=True)

In [119]:
ship.columns

Index(['PassengerId', 'Biswajit', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin'],
      dtype='object')

In [120]:
ship.drop(['Biswajit'], axis=1, inplace=True)

In [121]:
ship

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
4,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN
...,...,...,...,...,...,...,...,...,...,...
885,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
886,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42
887,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
888,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
889,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN

In [123]:
ship.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
4,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN
5,7,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46
6,8,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN
7,9,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN
8,10,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN
9,11,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6

In [124]:
ship.loc[40:50]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
40,42,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN
41,43,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN
42,44,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN
43,45,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,NaN
44,46,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN
45,47,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN
46,48,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN
47,49,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN
48,50,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN
49,51,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN
50,52,3,"Nosworthy, Mr. Richard Cater",male,21.0,0,0,A/4. 39886,7.8000,NaN

In [125]:
ship.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 890 entries, 0 to 889
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  890 non-null    int64
 1   Pclass       890 non-null    int64
 2   Name         890 non-null    object
 3   Sex          890 non-null    object
 4   Age          713 non-null    float64
 5   SibSp        890 non-null    int64
 6   Parch        890 non-null    int64
 7   Ticket       890 non-null    object
 8   Fare         890 non-null    float64
 9   Cabin        204 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 69.7+ KB

In [130]:
ship[ship.Cabin.isnull()]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
4,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN
6,8,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN
7,9,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN
...,...,...,...,...,...,...,...,...,...,...
883,885,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN
884,886,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN
885,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
887,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN

In [129]:
import numpy as np

In [132]:
ship.Cabin.replace(to_replace=np.nan, value='Unknown', inplace=True)

In [133]:
ship[ship.Cabin.isnull()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin]
Index: []

In [134]:
ship

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
4,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,Unknown
...,...,...,...,...,...,...,...,...,...,...
885,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Unknown
886,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42
887,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,Unknown
888,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
889,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Unknown

In [136]:
ship.Age.info()

<class 'pandas.core.series.Series'>
RangeIndex: 890 entries, 0 to 889
Series name: Age
Non-Null Count  Dtype
--------------  -----
713 non-null    float64
dtypes: float64(1)
memory usage: 7.1 KB

In [137]:
ship.Age.mean()

np.float64(29.691683029453014)

In [138]:
ship.Age.replace(np.nan,ship.Age.mean(), inplace=True)

In [139]:
ship

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,Unknown
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85
2,3,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,Unknown
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123
4,6,3,"Moran, Mr. James",male,29.691683,0,0,330877,8.4583,Unknown
...,...,...,...,...,...,...,...,...,...,...
885,887,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,Unknown
886,888,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42
887,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.691683,1,2,W./C. 6607,23.4500,Unknown
888,890,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148
889,891,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Unknown

In [143]:
ship.Parch.fillna(ship.Parch.mean(), inplace=True)

/tmp/ipython-input-143-1204957555.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ship.Parch.fillna(ship.Parch.mean(), inplace=True)

In [141]:
ship

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,Unknown
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85
2,3,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,Unknown
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123
4,6,3,"Moran, Mr. James",male,29.691683,0,0,330877,8.4583,Unknown
...,...,...,...,...,...,...,...,...,...,...
885,887,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,Unknown
886,888,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42
887,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.691683,1,2,W./C. 6607,23.4500,Unknown
888,890,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148
889,891,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Unknown

In [144]:
ship[ship.Age.duplicated()]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
13,15,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.000000,0,0,350406,7.8542,Unknown
15,17,3,"Rice, Master. Eugene",male,2.000000,4,1,382652,29.1250,Unknown
16,18,2,"Williams, Mr. Charles Eugene",male,29.691683,0,0,244373,13.0000,Unknown
18,20,3,"Masselmani, Mrs. Fatima",female,29.691683,0,0,2649,7.2250,Unknown
19,21,2,"Fynney, Mr. Joseph J",male,35.000000,0,0,239865,26.0000,Unknown
...,...,...,...,...,...,...,...,...,...,...
885,887,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,Unknown
886,888,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42
887,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.691683,1,2,W./C. 6607,23.4500,Unknown
888,890,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148
889,891,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Unknown

In [145]:
ship.Fare.drop_duplicates(inplace=True)

In [146]:
ship

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,Unknown
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85
2,3,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,Unknown
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123
4,6,3,"Moran, Mr. James",male,29.691683,0,0,330877,8.4583,Unknown
...,...,...,...,...,...,...,...,...,...,...
885,887,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,Unknown
886,888,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42
887,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.691683,1,2,W./C. 6607,23.4500,Unknown
888,890,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148
889,891,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Unknown